project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  typst:
    keep-typ: true
  jats: default
  docx: default

execute:
  freeze: true
